Load Packages

In [2]:
import numpy as np
import pandas as pd

Load Dataset

In [3]:
DS= pd.read_csv("breast-cancer-wisconsin.data 2",header= None)

In [4]:
DS.head()

0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

Adding Column Names

In [5]:
columns= ["V1","V2","V3","V4","V5","V6","V7","V8","V9","V10","V11"]

In [6]:
DS.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [7]:
DS.columns= columns

In [8]:
DS.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11'], dtype='object')

In [9]:
DS.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11
0  1000025   5   1   1   1   2   1   3   1    1    2
1  1002945   5   4   4   5   7  10   3   2    1    2
2  1015425   3   1   1   1   2   2   3   1    1    2
3  1016277   6   8   8   1   3   4   3   7    1    2
4  1017023   4   1   1   3   2   1   3   1    1    2

Missing Values

In [10]:
DS.isnull

<bound method DataFrame.isnull of           V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11
0    1000025   5   1   1   1   2   1   3   1    1    2
1    1002945   5   4   4   5   7  10   3   2    1    2
2    1015425   3   1   1   1   2   2   3   1    1    2
3    1016277   6   8   8   1   3   4   3   7    1    2
4    1017023   4   1   1   3   2   1   3   1    1    2
..       ...  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...
694   776715   3   1   1   1   3   2   1   1    1    2
695   841769   2   1   1   1   2   1   1   1    1    2
696   888820   5  10  10   3   7   3   8  10    2    4
697   897471   4   8   6   4   3   4  10   6    1    4
698   897471   4   8   8   5   4   5  10   4    1    4

[699 rows x 11 columns]>

In [11]:
DS.isnull().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
V6     0
V7     0
V8     0
V9     0
V10    0
V11    0
dtype: int64

The N/A values of the dataset is reported with "?"

In [12]:
DS= pd.read_csv("breast-cancer-wisconsin.data 2",header= None, na_values='?')

In [13]:
columns= ["V1","V2","V3","V4","V5","V6","V7","V8","V9","V10","V11"]

In [14]:
DS.columns= columns

In [15]:
DS.head()

V1  V2  V3  V4  V5  V6    V7  V8  V9  V10  V11
0  1000025   5   1   1   1   2   1.0   3   1    1    2
1  1002945   5   4   4   5   7  10.0   3   2    1    2
2  1015425   3   1   1   1   2   2.0   3   1    1    2
3  1016277   6   8   8   1   3   4.0   3   7    1    2
4  1017023   4   1   1   3   2   1.0   3   1    1    2

In [16]:
DS.isnull().sum()

V1      0
V2      0
V3      0
V4      0
V5      0
V6      0
V7     16
V8      0
V9      0
V10     0
V11     0
dtype: int64

Rows with Missing values

In [17]:
DS[DS.isnull().any(axis=1)]

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11
23   1057013   8   4   5   1   2 NaN   7   3    1    4
40   1096800   6   6   6   9   6 NaN   7   8    1    2
139  1183246   1   1   1   1   1 NaN   2   1    1    2
145  1184840   1   1   3   1   2 NaN   2   1    1    2
158  1193683   1   1   2   1   3 NaN   1   1    1    2
164  1197510   5   1   1   1   2 NaN   3   1    1    2
235  1241232   3   1   4   1   2 NaN   3   1    1    2
249   169356   3   1   1   1   2 NaN   3   1    1    2
275   432809   3   1   3   1   2 NaN   2   1    1    2
292   563649   8   8   8   1   2 NaN   6  10    1    4
294   606140   1   1   1   1   2 NaN   2   1    1    2
297    61634   5   4   3   1   2 NaN   2   3    1    2
315   704168   4   6   5   6   7 NaN   4   9    1    2
321   733639   3   1   1   1   2 NaN   3   1    1    2
411  1238464   1   1   1   1   1 NaN   2   1    1    2
617  1057067   1   1   1   1   1 NaN   1   1    1    2

Replacing the values of "V11" where 4--> 1, 2--> 0

In [18]:
DS['V11']= DS['V11'].map({4:1,2:0})

In [19]:
DS.head()

V1  V2  V3  V4  V5  V6    V7  V8  V9  V10  V11
0  1000025   5   1   1   1   2   1.0   3   1    1    0
1  1002945   5   4   4   5   7  10.0   3   2    1    0
2  1015425   3   1   1   1   2   2.0   3   1    1    0
3  1016277   6   8   8   1   3   4.0   3   7    1    0
4  1017023   4   1   1   3   2   1.0   3   1    1    0

In [20]:
DS.tail()

V1  V2  V3  V4  V5  V6   V7  V8  V9  V10  V11
694  776715   3   1   1   1   3  2.0   1   1    1    0
695  841769   2   1   1   1   2  1.0   1   1    1    0
696  888820   5  10  10   3   7  3.0   8  10    2    1
697  897471   4   8   6   4   3  4.0  10   6    1    1
698  897471   4   8   8   5   4  5.0  10   4    1    1

In [21]:
DS.sample(10)

V1  V2  V3  V4  V5  V6    V7  V8  V9  V10  V11
219  1223967   6   1   3   1   2   1.0   3   1    1    0
44   1103608  10  10  10   4   8   1.0   8  10    1    1
676  1365328   1   1   2   1   2   1.0   2   1    1    0
406  1231853   4   2   2   1   2   1.0   2   1    1    0
82   1143978   5   2   1   1   2   1.0   3   1    1    0
69   1121732   1   1   1   1   2   1.0   3   2    1    0
147  1185610   1   1   1   1   3   2.0   2   1    1    0
326   752904  10   1   1   1   2  10.0   5   4    1    1
5    1017122   8  10  10   8   7  10.0   9   7    1    1
500  1224565   6   1   1   1   2   1.0   3   1    1    0

Defining a Dataframe that will take dataframe as input and do logistic regression and return accuracy

STRATEGY 1: REMOVING ROWS AND MISSING VALUES

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [23]:
def mylogisticRegression(DS):
    x=DS.drop(columns=["V1","V11"])
    y=DS["V11"]
    x_train,x_test,y_train,y_test= train_test_split(x,y,test_size= 0.3,random_state=42)
    model=LogisticRegression()
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    accuracy= accuracy_score(y_test,y_pred)
    print(accuracy)
    
    #Creatig Confusion matrix
    
    pd.crosstab(y_test,y_pred,rownames=["Actual"],colnames=["Predicted"],margins= True)
    #Confusion matrix (x_test,y_tes)
    print(pd.crosstab(y_test,y_pred,rownames=["Actual"],colnames=["Predicted"],margins= True))

In [24]:
mylogisticRegression(DS.dropna())

0.9560975609756097
Predicted    0   1  All
Actual                 
0          125   2  127
1            7  71   78
All        132  73  205


STRATEGY 2: REPLACING MISSING VALUES WITH MEAN

In [25]:
DS2= DS.copy()
DS2= DS2.fillna(DS2.mean())
mylogisticRegression(DS2)

0.9523809523809523
Predicted    0   1  All
Actual                 
0          141   2  143
1            8  59   67
All        149  61  210


Different way of "Replacing Missing Values"

STRATEGY 2.1: REPLACING MISSING VALUES USING IMPUTER

In [26]:
from sklearn.impute import SimpleImputer

In [27]:
imputer= SimpleImputer(strategy="mean")
DS3= DS.copy()
DS3[["V7"]]=imputer.fit_transform(DS3[["V7"]])
mylogisticRegression(DS3)

0.9523809523809523
Predicted    0   1  All
Actual                 
0          141   2  143
1            8  59   67
All        149  61  210


STRATEGY 3: REPLACE MISSING VALUES WITH MEDIAN

In [28]:
imputer= SimpleImputer(strategy="median")
DS4=DS.copy()
DS4[["V7"]]=imputer.fit_transform(DS4[["V7"]])
mylogisticRegression(DS4)

#output did not match with Class

0.9666666666666667
Predicted    0   1  All
Actual                 
0          141   2  143
1            5  62   67
All        146  64  210


STRATEGY 4: REPLACE MISSING VALUES WITH MODE

In [29]:
imputer= SimpleImputer(strategy="most_frequent")
DS5=DS.copy()
DS5[["V7"]]=imputer.fit_transform(DS5[["V7"]])
mylogisticRegression(DS5)

0.9666666666666667
Predicted    0   1  All
Actual                 
0          141   2  143
1            5  62   67
All        146  64  210


 STRATEGY 5: REPLACE MISSING VALUES WITH a CONSTANT VALUES WITH SIMPLE IMPUTER

In [30]:
imputer= SimpleImputer(strategy="constant",fill_value=1)
DS6=DS.copy()
DS6[["V7"]]=imputer.fit_transform(DS6[["V7"]])
mylogisticRegression(DS6)

0.9666666666666667
Predicted    0   1  All
Actual                 
0          141   2  143
1            5  62   67
All        146  64  210


STRATEGY 6: REPLACING MISSING VALUES WITH KNN

In [31]:
from sklearn.impute import KNNImputer
imputer= KNNImputer(n_neighbors=3)
DS7=DS.copy()
DS7[["V7"]]=imputer.fit_transform(DS7[["V7"]])
mylogisticRegression(DS7)

0.9523809523809523
Predicted    0   1  All
Actual                 
0          141   2  143
1            8  59   67
All        149  61  210


In [32]:
#Go through the details of hyperparameter

STRATEGY 7: REPLACING MISSING VALUES WITH LINEAR REGRESSION WITH OTHER PREDICTORS

In [34]:
DS8=DS.copy()
train= DS8[DS8['V7'].notnull()]
test= DS8[DS8['V7'].isnull()]

In [35]:
train.shape

(683, 11)

In [36]:
test.shape

(16, 11)

In [40]:
from sklearn.linear_model import LinearRegression #Imported library
linReg= LinearRegression()
#model.fit(X,Y)
linReg.fit(train.drop(columns=["V7","V1","V11"]),train["V7"])

LinearRegression()

In [43]:
predictions= linReg.predict(test.drop(columns=["V7","V1","V11"]))

In [44]:
predictions

array([5.36606663, 8.22591014, 0.88928053, 1.66055745, 1.08993002,
       2.22087363, 2.78188891, 1.76056172, 2.12086936, 5.84594766,
       0.97967265, 2.39182817, 5.54199423, 1.76056172, 0.88928053,
       0.56870337])

In [45]:
#Rounding predictions
predictions= np.round(predictions,0)
predictions

array([5., 8., 1., 2., 1., 2., 3., 2., 2., 6., 1., 2., 6., 2., 1., 1.])

In [48]:
#Bringing the values of predictions into the missing places of V7
DS8.loc[DS8["V7"].isnull(),"V7"]=predictions

In [49]:
#CHECKING MISSING VALUES in DS8
DS8.isnull().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
V6     0
V7     0
V8     0
V9     0
V10    0
V11    0
dtype: int64

In [51]:
mylogisticRegression(DS8)

0.9523809523809523
Predicted    0   1  All
Actual                 
0          142   1  143
1            9  58   67
All        151  59  210


STRATEGY 8: REPLACING MISSING VALUES WITH LINEAR REGRESSION WITH PURTURBATION

In [54]:
DS9=DS.copy()
train= DS9[DS9["V7"].notnull()]
test= DS9[DS9["V7"].isnull()]

print(train.shape)
print(test.shape)

(683, 11)
(16, 11)


In [58]:
linRegPert= LinearRegression()
#model.fit(X,Y)
linRegPert.fit(train.drop(columns=["V7","V1","V11"]),train["V7"])

LinearRegression()

In [63]:
predictions= linRegPert.predict(test.drop(columns=["V7","V1","V11"]))
#Addition of perturbation
perturbed_predictions= predictions + np.random.normal(0,1,len(predictions))
print (perturbed_predictions)

[ 7.12772621  9.1243184   1.44436548  3.69355079  0.3790761   2.22596361
  5.16507989  2.18730218  2.23240399  7.20469059  0.15693649  2.96327236
  5.03314619  0.40432204 -0.43782241  2.0752497 ]


In [64]:
#rounding perturbed predictions
perturbed_predictions= np.round(perturbed_predictions,0)
print(perturbed_predictions)

#If less than 1, then replace with 1

perturbed_predictions [perturbed_predictions<1]=1

#If more than 10, then replace with 10

perturbed_predictions [perturbed_predictions>10]=10


DS9.loc[DS9["V7"].isnull(),"V7"]= perturbed_predictions

mylogisticRegression(DS9)

[ 7.  9.  1.  4.  0.  2.  5.  2.  2.  7.  0.  3.  5.  0. -0.  2.]
0.9523809523809523
Predicted    0   1  All
Actual                 
0          142   1  143
1            9  58   67
All        151  59  210


STRATEGY 9: REPLACING MISSING VALUES WITH MICE

In [67]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
DS10= DS.copy()
imputer= IterativeImputer()
DS10[["V7"]]=imputer.fit_transform(DS10[["V7"]])
mylogisticRegression(DS10)

0.9523809523809523
Predicted    0   1  All
Actual                 
0          141   2  143
1            8  59   67
All        149  61  210
